<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HWorld.WinForms</RootNamespace>
    <AssemblyName>HWorld.WinForms</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HWorld.Core\HWorld.Core.csproj" />
  </ItemGroup>
</Project>
